### ISSUE TITLE
Request Timeout for large image

### ISSUE THREAD

**Issue by rossingram** [HeyMaslo/companionserver#3]
Tried to process a single photo on the cloud demo (https://heymaslo.github.io/companionserver/demoAPI.html) and got 'request timeout'. Image I tried was 13mb, so may be the issue? Img here: https://we.tl/t-bvX5ph84qN

**Comment by un1crom** [comment]
you should check out the code and edit the timeout in index.js for analyzeMedia route.

alternatively really should abstract the timeout and filesize limits to API params or container config.

**Comment by un1crom** [comment]
> you should check out the code and edit the timeout in index.js for analyzeMedia route.
> 
> alternatively really should abstract the timeout and filesize limits to API params or container config.

then try it locally... then if it looks good.. merge it... then i'll push it to the cloud.

**Comment by un1crom** [comment]
there is now a variable that can be set in the API request for analyzeMedia and analyzeText

`timeOut=[INTEGER for milliseconds]`
