### ISSUE TITLE
Normalize Face Output

### ISSUE THREAD

**Issue by markziler** [HeyMaslo/companionserver#7]
Normalize all the facial output across face models to coordinate face analysis by specific face.  Specifically...

Refactor face code to use one algo to recognize faces and then do deeper facial analysis on each face recognized.  Make sure all output bounding boxes match up in test images.  Coordinate indexes in output array to consistently correspond to ordered faces.

**Comment by un1crom** [comment]
i have decided against reconciling the different face models into some unified model.

This is a post processing / post API work flow issue.  It would make the server more opaque to hide the details from downstream processes.  the face detection models are different and for different purposes.  reconciliation of any of it should happen post API response.
